# Generated by Django 4.2.9 on 2024-04-04 11:19

from django.db import migrations, models
import django.db.models.deletion
import gifts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=gifts.models.generate_code, max_length=4)),
                ('is_main', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopclient')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'db_table': 'gifts',
                'unique_together': {('shop', 'code')},
            },
        ),
    ]
