# Generated by Django 4.2.9 on 2024-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='gift_name',
            field=models.CharField(max_length=64),
        ),
    ]
