# Generated by Django 4.2.9 on 2024-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='birthdays_offer_after_nth_sale',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
