# Generated by Django 5.0.1 on 2024-01-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('telegram', '0002_bot_start_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopgroup',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.bot'),
        ),
    ]
