# Generated by Django 4.2.9 on 2024-02-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.user'),
        ),
    ]
