# Generated by Django 4.2.9 on 2024-02-13 14:11

from django.db import migrations, models
import shops.models.shop_products


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopclient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='shopproductcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.shop_products.get_shop_product_photo_path),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='shops.shopproductcategory'),
        ),
        migrations.DeleteModel(
            name='ShopProductPhoto',
        ),
    ]
