# Generated by Django 5.0.1 on 2024-01-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopgroup_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTemporaryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopclient')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopgroup')),
            ],
            options={
                'unique_together': {('client', 'group')},
            },
        ),
    ]
