# Generated by Django 4.2.9 on 2024-02-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shopclient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclient',
            name='shop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shopgroup'),
        ),
    ]
