# Generated by Django 4.2.9 on 2024-02-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_gift_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeinvitation',
            options={'verbose_name': 'employee invitation', 'verbose_name_plural': 'employee invitations'},
        ),
        migrations.AlterModelOptions(
            name='salecode',
            options={'verbose_name': 'sale code', 'verbose_name_plural': 'sale codes'},
        ),
        migrations.RemoveField(
            model_name='employeeinvitation',
            name='created_by',
        ),
    ]
