# Generated by Django 5.0.1 on 2024-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_each_nth_cup_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='each_nth_cup_free',
        ),
        migrations.AddField(
            model_name='shopgroup',
            name='each_nth_cup_free',
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
    ]
