# Generated by Django 5.0.1 on 2024-01-21 16:14

import shops.models.sale_temporary_codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_saletemporarycode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saletemporarycode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='saletemporarycode',
            name='code',
            field=models.CharField(default=shops.models.sale_temporary_codes.generate_code, max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='saletemporarycode',
            unique_together={('client', 'group', 'code')},
        ),
    ]
