# Generated by Django 4.2.9 on 2024-02-17 18:01

from django.db import migrations, models
import shops.models.shop_groups


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shopproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopgroup',
            name='gift_photo_url',
        ),
        migrations.AddField(
            model_name='shopgroup',
            name='gift_photo',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.shop_groups.get_gift_photo_path),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shops.shopproductcategory'),
        ),
    ]
