# Generated by Django 4.2.9 on 2024-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_employeeinvitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclient',
            name='born_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
