# Generated by Django 4.2.9 on 2024-01-23 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_shop_each_nth_cup_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletemporarycode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
