# Generated by Django 4.2.9 on 2024-01-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_saletemporarycode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsalesman',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
