# Generated by Django 4.2.9 on 2024-03-21 07:42

from django.db import migrations, models
import django.db.models.deletion
import shops.models.gift_codes
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopclient_born_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=shops.models.gift_codes.generate_code, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopclient')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name': 'gift code',
                'verbose_name_plural': 'gift codes',
                'unique_together': {('shop', 'code')},
            },
        ),
    ]
