# Generated by Django 5.0.1 on 2024-01-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_saletemporarycode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsalesman',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
