# Generated by Django 4.2.9 on 2024-02-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopgroup_gift_name_shopgroup_gift_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopgroup',
            name='is_menu_shown',
            field=models.BooleanField(default=False),
        ),
    ]
