# Generated by Django 4.2.9 on 2024-01-24 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shopsalesman_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopadmin')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
