# Generated by Django 4.2.9 on 2024-02-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_bot_start_text'),
        ('shops', '0005_shopgroup_is_menu_shown'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopclient',
            unique_together={('user', 'shop_group')},
        ),
    ]
