# Generated by Django 4.2.9 on 2024-01-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_salesmaninvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmaninvitation',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
