# Generated by Django 4.2.9 on 2024-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('start_text', models.TextField(max_length=4096)),
                ('sale_created_text', models.TextField(default='✅ Код успешно применен!\n🔥 Для получения подарка осталось совершить ещё {count} покупок', max_length=4096)),
                ('gift_given_text', models.TextField(default='🎉 Поздравляем! Вы получили подарок!', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.CheckConstraint(check=models.Q(('sale_created_text__contains', '{count}')), name='bot_sale_created_text_contains_count', violation_error_message='Sale created text must contain "{count}"'),
        ),
    ]
