# Generated by Django 4.2.9 on 2024-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='start_text',
            field=models.TextField(default='Привет! ☺️ Мы рады что ты с нами и в благодарность мы готовы дарить тебе кофе бесплатно!\nМы будем стараться, делать наш сервис все лучше и лучше, чтобы тебе хотелось возвращаться к нам. А сейчас нажми кнопку меню чтобы отметить свою первую покупку кофе! ☕️', max_length=4096),
        ),
    ]
