# Generated by Django 4.2.9 on 2024-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='gift_given_text',
            field=models.TextField(default='🎉 Поздравляем! Вы получили подарок!', max_length=4096),
        ),
        migrations.AddField(
            model_name='bot',
            name='sale_created_text',
            field=models.TextField(default='✅ Код успешно применен!\n🔥 Для получения подарка осталось совершить ещё {count} покупок', max_length=4096),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.CheckConstraint(check=models.Q(('sale_created_text__contains', '{count}')), name='bot_sale_created_text_contains_count', violation_error_message='Sale created text must contain "{count}"'),
        ),
    ]
