# Generated by Django 5.0.1 on 2024-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='start_text',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
