# Generated by Django 5.0.1 on 2024-01-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_bot_start_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
