# Generated by Django 4.2.9 on 2024-02-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_bot_start_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='start_text_client_web_app',
            field=models.TextField(default='Мы с удовольствием угостим бесплатным кофе, приходи к нам почаще и копи свои бонусы, ведь каждая N-я кружка кофе в подарок!', max_length=4096),
        ),
    ]
