# Generated by Django 5.0.1 on 2024-01-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
